# Generated by Django 2.1.3 on 2018-11-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_text', models.CharField(max_length=300)),
                ('price_value', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=500)),
                ('precio', models.DecimalField(decimal_places=2, default='', max_digits=10)),
                ('url', models.CharField(default='', max_length=500)),
                ('image', models.CharField(default='', max_length=500)),
                ('modelo', models.CharField(default='', max_length=500)),
                ('marca', models.CharField(default='', max_length=200)),
                ('direccion', models.CharField(default='', max_length=500)),
                ('categoria', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
