# Generated by Django 2.1.3 on 2018-11-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_product_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tienda',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='producto',
            name='url_tienda',
            field=models.CharField(default='', max_length=500),
        ),
    ]
