# Generated by Django 2.2.dev20181022192133 on 2018-10-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_text', models.CharField(max_length=300)),
                ('price_value', models.IntegerField(max_length=200)),
                ('url_text', models.CharField(max_length=500)),
            ],
        ),
    ]
